### ISSUE TITLE
Clockwork RNN missing in current version

### ISSUE THREAD

**Issue by akansal1** [fchollet/keras#2669]
Hello,
There is an old PR #1112 for clockwork RNN implementation in Keras, but I am not able to find in it current version of Keras. Can anyone point me in right direction?

thanks

**Comment by braingineer** [comment]
This looks interesting. I'll port it quickly.

**Comment by braingineer** [comment]
this might work. It compiles and runs, I make no promises about performance.  Could you test it out and see?

https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py

**Comment by akansal1** [comment]
Hey @braingineer , thanks for porting, I was unable to run it at my end. I am trying to implement it on a time series regression problem, where I have 4 independent features and an dependent feature which in my case is temperature, i am convert my data into a 3d array (samples, timesteps,features) for lstm, I am using same logic here:
```python
model1 = Sequential()
model1.add(ClockworkRNN(output_dim=150,period_spec=[16,32,72],
           input_shape=(72, 4),
           dropout_W = 0.4,
           return_sequences=True))
model1.add(Dropout(.2))
model1.add(TimeDistributed(Dense(output_dim=1, activation='linear')))
model1.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
```
My data shape is _(4249, 72, 4) &  (4249, 72, 1)_ respectively

Part of long error msg I am getting is:

```python
ValueError: Input dimension mis-match. (input[1].shape[1] = 4, input[3].shape[1] = 150)
Apply node that caused the error: Elemwise{Composite{Switch(EQ((i0 % i1), i2), tanh(i3), i4)}}(InplaceDimShuffle{x,x}.0, <TensorType(float32, matrix)>, TensorConstant{(1, 1) of 0.0}, Gemm{no_inplace}.0, <TensorType(float32, matrix)>)
Toposort index: 4
Inputs types: [TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1, 1), (1, 4), (1, 1), (1, 150), (1, 150)]
Inputs strides: [(4, 4), (16, 4), (4, 4), (600, 4), (600, 4)]
Inputs values: [array([[ 0.]], dtype=float32), array([[ 1.66666663,  0.        ,  0.        ,  0.        ]], dtype=float32), array([[ 0.]], dtype=float32), 'not shown', 'not shown']
Outputs clients: [['output', ViewOp(Elemwise{Composite{Switch(EQ((i0 % i1), i2), tanh(i3), i4)}}.0)]]
```

**Comment by braingineer** [comment]
Hmm. I'm not sure, but I do see another bug. I did some quick sublime copy keystroke stuff earlier and left a variable or two where they shouldn't be. the first that I notice is that periods accidentally got set to `K.variable(mask...)` so that's a problem.

I'm fighting a computer meltdown thing (just got done reformatting. sweet stuff), but I'll try to help debug soon.

**Comment by akansal1** [comment]
Thanks, I figured out problem in my input as well, I read your code to restructure input's period_spec:

```python
model1 = Sequential()
model1.add(ClockworkRNN(output_dim=150,period_spec=[1,18,36],
           input_shape=(72, 4),
           return_sequences=True))
model1.add(Dropout(.2))
model1.add(TimeDistributed(Dense(output_dim=1, activation='linear')))
model1.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
```
The code runs but does not converge, I guess bugs figured out by you may correct the issue

Thanks

**Comment by akansal1** [comment]
@braingineer in your code, I am not able to understand following lines:

```python
def step(self, x, states):
        prev_output = states[0]
        time_step = states[1]
        B_U = states[1]
        B_W = states[2]
        period = states[3]
```
I am not able to understand where ```states``` is getting updated in whole code, as per code above you are assuming  length of states = 4 
I have not implemented custom layer before so have limited understanding

**Comment by braingineer** [comment]
Hi @akansal1 

The way states is determined is most easily demonstrated by peeking at the theano backend.  It's a bit hard to understand because theano's scan operation takes some getting used to, but I'll help break it down:

```python
            def _step(input, mask, output_tm1, *states):
                output, new_states = step_function(input, states)
                # output previous output if masked.
                output = T.switch(mask, output, output_tm1)
                return_states = []
                for state, new_state in zip(states, new_states):
                    assert mask.ndim == new_state.ndim == state.ndim
                    return_states.append(T.switch(mask, new_state, state))
                return [output] + return_states

            results, _ = theano.scan(
                _step,
                sequences=[inputs, mask],
                outputs_info=[initial_output] + initial_states,
                non_sequences=constants,
                name='{}_scan'.format(inputs.name),
                go_backwards=go_backwards)
```
This is the masked and rolled version of scan.   The other options are to unroll it, in which case `theano.scan` is not used at all, but rather the entire computation graph is linked up at once; and to not mask it, in which case the scan operation just gets easier.  

so, some explanations, top to bottom:
- `_step` is a wrapper around the RNN step function so that it can handle th emask
- `*states` is a python trick that disguises what is actually going on; I'll explain that in a minute. but for now, just assume that the correct number of states are passed in here
- `input, mask` refer to the two things passed into `sequences` in the scan function
- `state_tm1` refers to the first part of `outputs_info`.  
- the rest of this function is just using the step function calculate the masked next step

to explain scan:
- the order of the arguments scan passes to the function `_step` are as follows:
- each time step of sequences (`input` and `mask`)
- each time offstep item from `outputs_info`.  
    + `outputs_info` specifies the shape of the outputs and also the shape of the time offset item that should be passed **back** into the `_scan` function at every timestep
- there's fancy stuff that can be used here to get more than just `t-1`, but in this exact instance, `[initial_output]+initial_states` is passing the states defined in `get_initial_states`.  
    + in keras, `get_initial_states` is defined as `[initial_state for _ in range(len(self.states))]`
    + in the cwrnn, we define `self.states = [None, None]` in the `self.build` function
- this adds `output_tm1` from the `initial_output`
- it adds `state0_tm1` and `state1_tm1` (colloquially labeled here).  these are implicitly grabbed by the `*states` fanciness
    + importantly, you can check what these are by either looking at the `get_initial_states` function **or** by looking at the `step` function in the rnn itself---`return output, [output, time_step+1]`---because this is supposed to be returning `output, new_states`
    + in fact, looking at either spot (`get_initial_states` or `step_function`'s output) should exactly match the other
- **finally**, and I think the source of the confusion, is that `scan` also passes in the constants at every timestep
- the constants in `SimpleRNN` are just the bayesian dropout masks
- However, I've added the `period` information to it:
```python
    def get_constants(self, x):
        consts = super(ClockworkRNN, self).get_constants(x)
        consts.append(self.period)
        return consts
```
- So, `constants` contributes 3 items to the set of things passed into `_step`

Putting it all together, we have:
- `input`
- `mask`
- `output_tm1`
- `state0_tm1`
- `state1_tm1`
- `const0` which is `B_U`
- `const1` which is `B_W`
- `const2` which is `period`

with the python fanciness of `_step(input, mask, output_tm1, *states)`, the above turns into
- `input`
- `mask`
- `output_tm1`
- `(state0_tm1, state1_tm1, const0, const1, const2)`

and it's this last one, which is now `states` that unpacks into the things you were asking about. 


hope that helps

**Comment by akansal1** [comment]
@braingineer thanks a lot for such a detailed explanation it helped a lot in understanding the flow, in code ```time_step``` & ```B_U``` are sharing same states:

```python
def step(self, x, states):
        prev_output = states[0]
        time_step = states[1]
        B_U = states[1]
        B_W = states[2]
        period = states[3]
```

as per your explanation above, code should change to 

```python
def step(self, x, states):
        prev_output = states[0]
        time_step = states[1]
        B_U = states[2]
        B_W = states[3]
        period = states[4]
```

**Comment by braingineer** [comment]
You're completely right!  Thanks for catching that!

**Comment by akansal1** [comment]
@braingineer  thanks a lot, I just tried on my sample data and it is converging, probably it will work now

there is another repository with some older keras implementations for [various RNN model](https://github.com/gaoyuankidult/einstein/blob/master/einstein/layers/recurrent.py):

thanks again

**Comment by gw0** [comment]
Why don't you make a PR to add CW-RNN to Keras?

**Comment by talpay** [comment]
It would have to be ported to the new backend and tested. This issue is high on my priority list, however. I might make a PR soon unless someone gets to it before me.

**Comment by gw0** [comment]
@talpay Yes, but for CW-RNN the version of @braingineer (https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py) is already ported to the new backend. It just needs to be tested and PR made.

**Comment by braingineer** [comment]
If someone wants to just on the tests and stuff to make it done sooner, that'd be great. Otherwise, I'm swamped to really contribute anything soon. I've added to my google calendar in case it's not done when my next down period starts.

**Comment by vinayakumarr** [comment]
Not able to save checpointer and as well as model. This is showing the following error

AttributeError: 'ClockworkRNN' object has no attribute 'periods'

**Comment by braingineer** [comment]
should be `period` not `periods`

period is creating here: 

https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py#L39

but referenced as `self.periods` in the get_config.

**Comment by Cogitans** [comment]
Apart from the above-mentioned issue, does anyone know the current status of this CW-RNN implementation? I would like to know if I have to implement my own or if there is an implementation I can use.

**Comment by braingineer** [comment]
@Cogitans as far as I know, it should be working.  Others were using it and didn't report any issues.  If you find anything wrong, let me know and I'll help fix it.

**Comment by Cogitans** [comment]
Thank you so much! Can you help explain to me the following lines
` def get_initial_states(self, x):
        initial_states = super(ClockworkRNN, self).get_initial_states(x)
        if self.go_backwards:
            input_length = self.input_spec[0].shape[1]
            initial_states[-1] = float(input_length)
        else:
            initial_states[-1] = K.variable(0.)
        return initial_states`

Specifically, the " initial_states[-1] = K.variable(0.)". Tensorflow is throwing an error because in the TF backend keras calls "tf.concat(1, states)", where states are the initial states, and the dimension of the variable doesn't fit with the other state (I get a "rank 2 not compatible with rank 0" error). Thanks!

**Comment by braingineer** [comment]
Hmm. I'm actually not sure, and kind of forgot about the issue on the repo (in the midst of writing my dissertation and getting overwelmed is a weekly routine).  

I'll ping back again tomorrow after I've looked at it. I will probably have questions for you about TF, since I'm in the exact opposite boat: all of my neural net/computational graph stuff has been theano. 

B.

**Comment by vinayakumarr** [comment]
After changing to period, still getting same error. Could you please tell how to correct it. Code iw working properly but i am not able to save the each epoch checkpoints

**Comment by braingineer** [comment]
Hi @vinayakumarr , I think the fix with self.periods should have worked.  Notice the plural. 

However, today I'm intalling tensorflow & debugging this implementation.  

Cheers.

**Comment by Cogitans** [comment]
I think I can propose a solution. The fundamental issue seems to be that Keras (at least the TF backend) assumes all Tensors passed in the states variable are of equal rank. This Variable(0.) (which represents the time step) obviously breaks that.

Keras does however, have support for constants being passed around. If we override "get_constants" in Clockwork to pass around this variable instead of putting it in states then I think that will solve the problem. Does this seem logical?

**Comment by braingineer** [comment]
Hi @Cogitans 

I'm tracking down exactly where in the tensorflow_backend.rnn code that happens, but I'm having some issues with updating nvidia drivers (it's always a pain.. and tensorflow wanted 8.0 while I was still using 7.5) and libraries (I haven't merged keras master into my dev branch in a couple weeks).  Can you point at the code where the error is throwing?   The one that's linked onto my repo is from an older version and doesn't match current backend code. 

The one thing I worry about with using it as a constant is that constants aren't updated value-wise in theano.  Constants, instead, are passed in as non-sequences, which essentially just makes them available as-is.   

One possible hack is to make the 0-variable the same size as the weights matrix, and then increment that.  You lose 16 bits * size of matrix, but that shouldn't be too horrible.  But this solution seems gross. 

I'm also not grokking some of the tensorflow design decisions.  It's not immediately obvious what their recurrent steps assume about how variables change.  

I should have the libraries up and running soon-ish.

**Comment by Cogitans** [comment]
Apologies for taking so long to follow up. 

I didn't know that about Theano, but that's a good reason not to use the constants field. I also thought about the padding solution, I think that might be a feasible solution, especially because I took have done some digging into TF rnn code and am equally bewildered. I'll keep looking into it, but it the meantime I might try cooking up that quick hack to the time constant and see if that fixes it.

**Comment by Cogitans** [comment]
Update on that. I got Clockwork working on tensorflow, but I have a few notes.
1) I did the hacky tensor-of-scalar thing; not ideal but it worked.
2) The keras tensorflow backend uses tf.cond for K.switch, instead of tf.select. I'm not sure why. Using K.switch causes Clockwork to crash but if you manually call tf.select (the way you would expect it to be called in K.switch) then everything works fine. I would love to see an explanation for what K.switch works the way it does to understand it better.

Also, Tensorflow's modulus operator doesn't seem to work on a gpu, does anyone happen to know why?

With the change to the scalar variable, it should be all good to go, **except** the K.switch thing. I'm rather new to pull requests/github issue threads, is there anywhere I could ask about why K.switch is written the way it it?

**Comment by gw0** [comment]
@Cogitans You could find the problematic file on GitHub, turn on "Blame" mode that find out who put the `K.switch` there. Otherwise post to Google Group or ask on Gitter chat.

**Comment by chaxor** [comment]
I wanted to provide the solution I found for getting the Clockwork RNN working on keras 2.0.6 using tensorflow here.  I am not absolutely certain it is correct, but it does run.
I added the following code to the keras recurrent layers module here: `keras/layers/recurrent.py` underneath the site-packages folder: `~/anaconda3/lib/python3.5/site-pacakges/`.

This code was added to the bottom of the `recurrent.py` file:

```

# https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py
# modified for keras 2.0
        # self.U is now self.recurrent_kernel
        # self.W is now self.kernel
        # self.b is now self.bias
class ClockworkRNN(SimpleRNN):
    '''
        Clockwork Recurrent Unit - Koutnik et al. 2014

        Clockwork RNN splits simple RNN neurons into groups of equal sizes.
        Each group is activated every specified period. As a result, fast
        groups capture short-term input features while slow groups capture
        long-term input features.

        References:
            A Clockwork RNN
                http://arxiv.org/abs/1402.3511
    '''
    def __init__(self, units, period_spec=[1], **kwargs):
        self.units = units
        assert units % len(period_spec) == 0, ("ClockworkRNN requires the units to be " +
                                                "a multiple of the number of periods; " +
                                                "units %% len(period_spec) failed.")
        self.period_spec = np.asarray(sorted(period_spec, reverse=True))
       
        super(ClockworkRNN, self).__init__(units, **kwargs)

    def build(self, input_shape):

        ### construct the clockwork structures
        ### basically: every n units the period changes;
        ### `period` is for flaggin this; `mask` is for enforcing it
        n = self.units // len(self.period_spec)
        mask = np.zeros((self.units, self.units), K.floatx())
        period = np.zeros((self.units,), np.int16)
        for i, t in enumerate(self.period_spec):
            mask[i*n:(i+1)*n, i*n:] = 1
            period[i*n:(i+1)*n] = t
        self.mask = K.variable(mask, name='clockword_mask')
        self.period = K.variable(period, dtype='int16', name='clockwork_period')

        super(ClockworkRNN, self).build(input_shape)

        # self.U is now self.recurrent_kernel
        # self.W is now self.kernel
        # self.b is now self.bias
        self.recurrent_kernel = self.recurrent_kernel * self.mask  ### old implementation did this at run time... 

        ### simple rnn initializes the wrong size self.states
        ### we want to also keep the time step in the state. 
        if self.stateful:
            self.reset_states()
        else:
            self.states = [None, None]



    def get_initial_states(self, x):
        initial_states = super(ClockworkRNN, self).get_initial_states(x)
        if self.go_backwards:
            input_length = self.input_spec[0].shape[1]
            initial_states[-1] = float(input_length)
        else:
            initial_states[-1] = K.variable(0.)
        return initial_states


    def reset_states(self):
        assert self.stateful, 'Layer must be stateful.'
        input_shape = self.input_spec[0].shape
        if not input_shape[0]:
            raise Exception('If a RNN is stateful, a complete ' +
                            'input_shape must be provided (including batch size).')

        if self.go_backwards:
            initial_time = self.input_spec[0].shape[1]
        else:
            initial_time = 0.

        if hasattr(self, 'states'):
            K.set_value(self.states[0],
                        np.zeros((input_shape[0], self.units)))
            K.set_value(self.states[1], initial_time)
        else:
            self.states = [K.zeros((input_shape[0], self.units)), K.variable(initial_time)]

    def get_constants(self, x, training = None):
        consts = super(ClockworkRNN, self).get_constants(x, training = None)
        consts.append(self.period)
        return consts

    def step(self, x, states):
        prev_output = states[0]
        time_step = states[1]
        B_U = states[2]
        B_W = states[3]
        period = states[4]

        # if self.consume_less == 'cpu':
        #     h = x
        # else:
        #     h = K.dot(x * B_W, self.kernel) + self.bias

        h = x

        output = self.activation(h + K.dot(prev_output * B_U, self.recurrent_kernel))
        
        if (K.backend() == 'tensorflow'):
            import tensorflow as tf

            output = tf.where(K.equal(tf.cast(time_step, tf.float32) % tf.cast(period, tf.float32), 0.), output, prev_output)
        else:
            output = K.switch(K.equal(time_step % period, 0.), output, prev_output)
            
        
        return output, [output, time_step+1]


    def get_config(self):
        config = {"periods": self.periods}
        base_config = super(CWRNN, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))



```
The main changes made compared to the original from @braingineer at `https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py` are `output_dim` is now called `units`, `self.U` is now `self.recurrent_kernel`, `self.b` is `self.bias` and `self.W` is `self.kernel`.  In addition, I made the alteration for `K.switch` to `tf.where` and used `tf.cast` where it helped get rid of some errors (some of these attempts were just guesses at how to solve the issues).

I also wasn't sure how to deal with the `self.consume_less` property, so I just took out the functionality since it was causing errors. 

My use of the layer was simply `ClockworkRNN(units = seq_len, period_spec = [1.,2.,4.,8.], return_sequences=True)(char_in)`, where `char_in` is a tensor of shape (?, 2048, 16) (seq_len=2048).  
If anyone has improvements to this, I, and likely many others, would love to hear about them.

**Comment by chaxor** [comment]
Update on the code above - I wasn't able to get a Bidirectional layer wrapper to work with the CWRNN layer.  It seems like the issue is due to not know what shape the output is when initializing, but I haven't been able to fix it.  I was wondering if anyone such as @braingineer had any ideas for how to fix that issue?

**Comment by dzhu622911** [comment]
@chaxor, Thanks a lot for your code, I read carefully the keras source code of RNN part and found something confusing.

here is the inheritance relationship:
Layer --> RNN --> SimpleRNN -->ClockworkRNN
              
And SimpleRNNCell is an attribute of RNN, means RNN.cell = SimpleRNNCell;
Further, kernel, recurrent_kernel and bias are the attribute of  SimpleRNNCell;
So The question is in your code, you directly use the 
  self.recurrent_kernel
But if my understanding is right, according to above inheritance relationship, RNN class doesn't have the recurrent_kernel attribute, it may be self.cell.recurrent_kernel;

Is that right ?

**Comment by DeanIsMe** [comment]
I've spent some time implementing a CWRNN on Keras, which used some code from @chaxor's comment for inspiration.
It's pretty difficult to verify that it's actually doing what the paper describes, so please let me know how it goes for you.
https://github.com/DeanIsMe/Keras_Objects/blob/master/ClockworkRNN.py

**Comment by dzhu622911** [comment]
@DeanIsMe , That is great work, actually i am doing the same thing, write the ClockworkRNNCell(Layer) and ClockworkRNN(RNN), but i just finish the ClockworkRNNCell. 

I submitted the issue of solution proposal of  CWRNN tensorflow code written by Tom.

when i compare the tf code of tom and the Recurrent.py code of keras library, i found several points:
1. The neutrons connection of CWRNN is different with SimpleRNN, SimpleRNN is fully interconnected,
but CWRNN just fully interconnected in each group, and the connection rule between groups is, when Tj > Ti, then group j should connect group i, that is the reason of upper triangle matrix mask.

2. In tom's code, us tf.slice to only calculate the valid group (i called the valid group means timestep % group_period == 0) in the whole (self.units, self.units) matrix, but not calculate the invalid group; 
But in Chaxor code, because inherit the SimpleRNN, it calculates the whole (self.units, self.units) matrix,
(that maybe waste the computer), and once finished the calculation, use k.switch to combinate the output of valid group and pre_output of invalid group.

In my ClockworkRNNCell code, i remove the dropout, because i think the CWRNN doesn't need dropout, 
you can change the self.units and the len(period) to replace dropout.

for now, i can't find the tf.slice wrapped in keras, so i still calculate the whole (self.units, self.units) matrix, but i add a timestep_mask which will be used to multiply to W_I (weight input)and W_H(weight Hidden), that makes the invalid group weight to be 0, and may make the calculation much easier;

but your split_method is really working to replace the tf.slice, that is great, i will spend time to read carefully you code and pay time to test it.

**Comment by DeanIsMe** [comment]
I write the split_method to be more efficient, as it only performs the calculations that are needed for that step. However, I was surprised to find that it was actually slower (about 24% more time for my test case).

**Comment by dzhu622911** [comment]
@DeanIsMe, i misunderstanding in you "state to output", you add a new param "recurrent_activation";

I think you involved additional computing in:
```
        # Calculate Output
        output = K.dot(hidden, self.recurrent_kernel_o)
        if self.activation is not None:
            output = self.activation(output)
```
i am not sure why you compute output in cell.call which will be runned by step ?
below is the tensorflow reference code from tom:
```
            self.state = tf.get_variable("state", shape=[self.config.batch_size, self.config.num_hidden], initializer=tf.zeros_initializer(), trainable=False)

            for time_step in range(self.config.num_steps):

                # Only initialize variables in the first step
                if time_step > 0: scope.reuse_variables()

                # Find the groups of the hidden layer that are active
                group_index = 0
                for i in range(len(self.clockwork_periods)):
                    # Check if (t MOD T_i == 0)
                    if time_step % self.clockwork_periods[i] == 0:
                        group_index = i+1  # note the +1

                # the real index of group in matrix
                group_index = self.group_size * group_index

                # Compute (W_I*x_t + b_I)
                WI_x = tf.matmul(x_list[time_step], tf.slice(self.input_W, [0, 0], [-1, group_index]))
                WI_x = tf.nn.bias_add(WI_x, tf.slice(self.input_b, [0], [group_index]), name="WI_x")

                # Compute (W_H*y_{t-1} + b_H), note the multiplication of the clockwork mask (upper triangular matrix)
                self.hidden_W = tf.multiply(self.hidden_W, self.clockwork_mask)
                WH_y = tf.matmul(self.state, tf.slice(self.hidden_W, [0, 0], [-1, group_index]))
                WH_y = tf.nn.bias_add(WH_y, tf.slice(self.hidden_b, [0], [group_index]), name="WH_y")

                # Compute y_t = (...) and update the cell state
                y_update = tf.add(WH_y, WI_x, name="state_update")
                y_update = activation_hidden(y_update)

                # Copy the updates to the cell state
                self.state = tf.concat(
                    axis=1, values=[y_update, tf.slice(self.state, [0, group_index], [-1,-1])])

            # Save the final hidden state
            self.final_state = self.state

            # Compute the output, y = f(W_O*y_t + b_O)
            self.predictions = tf.matmul(self.final_state, self.output_W)
            self.predictions = tf.nn.bias_add(self.predictions, self.output_b)
``` 

The output computing is out of the scope in step computing cycle.

**Comment by dzhu622911** [comment]
@DeanIsMe, another concern is regarding the 'time_step' in CWRNNCell.call, i can't find where do initialization to time_step. 

i am not sure, maybe need to overwrite the get_initial_state(), or directly pass the initial_state by RNN.__call__

**Comment by dzhu622911** [comment]
And should also consider stateful, the real states in cwrnn.step() is [state, timestep];
when stateful = true, need only reserve compute state, but the timestep should init to 0;

in RNN(layer).call of recurrent.py code:
```
    def call(self,
             inputs,
             mask=None,
             training=None,
             initial_state=None,
             constants=None):
        # input shape: `(samples, time (padded with zeros), input_dim)`
        # note that the .build() method of subclasses MUST define
        # self.input_spec and self.state_spec with complete input shapes.
        if isinstance(inputs, list):
            inputs = inputs[0]
        if initial_state is not None:
            pass
        elif self.stateful:
            initial_state = self.states
        else:
            initial_state = self.get_initial_state(inputs)
```
because the initial_state process inside the RNN.call, and once set the stateful, we should reserve the state and reset the timestep to 0;

If don't modify above code, i think we need to modify the return of CWRNNCell.call() to 
return output, [output, (timestep + 1) % sequence_len];
sequence length means the total steps of one sequence;

also need to overwrite reset_states

**Comment by DeanIsMe** [comment]
I'm on holidays at the moment. But I'll go through it all when I get home on Sunday.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dzhu622911** [comment]
I have finished my code and put them in:
https://github.com/dzhu622911/nn-keras-cwrnn
and also a tf version code base on tomrunia's code 
https://github.com/dzhu622911/nn-tf-cwrnn

welcome to review and check these code.

**Comment by dzhu622911** [comment]
I have finished my code and put them in:
https://github.com/dzhu622911/nn-keras-cwrnn
and also a tf version code base on tomrunia's code 
https://github.com/dzhu622911/nn-tf-cwrnn

welcome to help to review and check these code.

**Comment by DeanIsMe** [comment]
Ok back home. Thanks @dzhu622911 for reviewing my code.
> The output computing is out of the scope in step computing cycle.

It seems that in Tensorflow the state updates are in a separate block to the output calculations. However, I believe that the .call function in Keras must return the output and the state. See SimpleRNNCell.call() in recurrent.py:
```
def call(self, inputs, states, training=None):
        ...
        output = h + K.dot(prev_output, self.recurrent_kernel)
        if self.activation is not None:
            output = self.activation(output)
        ...
        return output, [output]
```

> i can't find where do initialization to time_step

The get_initial_state() function in RNN() initialises all states to 0. Therefore, I did not need to redefine this function. Note that the state size is set up in CWRNNCell.__init__() with the line
`self.state_size = [self.units, 1]`

> If don't modify above code, i think we need to modify the return of CWRNNCell.call() to
return output, [output, (timestep + 1) % sequence_len];

I don't understand why timestep should be reset to 0 after each sequence. I'm using the K.tf.mod() function to determine which states to update, which will continue to work when timestep increments beyond sequence_len.

> also need to overwrite reset_states

What for? The default RNN.reset_states() sets all state values to 0. This is what we want.

**Comment by dzhu622911** [comment]
@DeanIsMe,  I think i am understood you intension, Thanks a lot for your reply.
