### ISSUE TITLE
What would be the output shape of cosine/dot product merge of 2 layers?

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#878]
I am trying to add 2 new merge modes, cosine and dot:

#cosine merge:

elif self.mode == 'cos':
            l1 = self.layers[0].get_output(train)
            l2 = self.layers[1].get_output(train)
            output, _ = theano.scan(lambda v1,v2 : T.dot(v1,v2)/T.sqrt(T.dot(v1,v1) * T.dot(v2,v2)) , sequences= [r1, r2], outputs_info = None)
            return output            

#dot merge:
elif self.mode == 'dot':
            l1 = self.layers[0].get_output(train)
            l2 = self.layers[1].get_output(train)
            output, _ = theano.scan(lambda v1,v2 : T.dot(v1,v2), sequences= [r1, r2], outputs_info = None)
            return output            
else:
            raise Exception('Unknown merge mode')

What would be their corresponding output shapes?

**Comment by dbonadiman** [comment]
It depends on the shape of the inputs, however if the input is the output of two  Dense layer the scan dot output is.

(Batch_size , 1) that is basically the same size of 
```
output_shape = (l1.output_shape[0], 1)
```

I found really funny that you asked this today just 3 hours later i implemented a first naive implementation of the same thing.
By the way you can use the batched dot to do the trick and remember to dimshuffle the output since the output shape of the function is always a vector in the form (Batch_size,) but you need (Batch_size, 1).

Here is my code, is not ready to pull i just checking everything is fine:

https://github.com/dbonadiman/keras/blob/debugging-dot/keras/layers/core.py#L336

**Comment by farizrahman4u** [comment]
Seems like you missed the following commits:
569bb74
6f62071

**Comment by dbonadiman** [comment]
Yeah i need to update my local version

**Comment by lemuriandezapada** [comment]
I don't really get what that "join" mode does. There's no documentation on it.
